name: flutter_cleaner
description: "Broomie - Clean up mobile development artifacts for Flutter and React Native developers"

version: 5.0.0+5

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.8.3
  file_picker: ^10.3.2
  url_launcher: ^6.2.5

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/images/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/